import React from 'react';
import {
  UserCircle,
  Settings,
  Bell,
  Star,
  Database,
  Monitor,
  Activity,
  Wifi,
  Bug,
  List,
  RefreshCw,
  LineChart,
  LayoutGrid,
  HelpCircle,
  Check,
  Pencil,
  Plug,
  Plus,
  PlusCircle,
  Loader2,
  CheckCircle,
  Clock,
  AlertTriangle,
  X,
  XCircle,
  Github,
  Copy,
  Files,
  File,
  GitBranch,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Eye,
  EyeOff,
  Trash2,
  Download,
  Upload,
  Search,
  Folder,
  FolderOpen,
  Code,
  Terminal,
  Play,
  Pause,
  Square,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  MoreVertical,
  Info,
  Lock,
  Unlock,
  Link,
  Link2Off,
  Cloud,
  Sun,
  Moon,
  Palette,
  Sliders,
  Filter,
  ArrowUpAZ,
  ArrowDownZA,
  Type,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Image,
  StickyNote,
  Book,
  Bookmark,
  Calendar,
  RotateCw,
  RotateCcw,
  Share,
  LogOut,
  LogIn,
  Mic,
  MicOff,
  Volume2,
  VolumeX,
  Cpu,
  HardDrive,
  CreditCard,
  Wallet,
  Package,
  Archive,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Plane,
  Anchor,
  AtSign,
  BatteryCharging,
  BatteryFull,
  MessageSquare,
  FilePlus,
  FolderPlus,
  Circle,
  Smartphone,
  Tablet,
  Laptop,
  MousePointerClick,
  QrCode,
  Maximize,
  Minimize,
  ExternalLink,
  Save,
  History,
  PanelLeft,
  CloudDownload,
  LockKeyholeOpen,
} from 'lucide-react';

const iconMap: Record<string, any> = {
  'user-circle': UserCircle,
  'gear-six': Settings,
  'gear': Settings,
  'settings': Settings,
  'bell': Bell,
  'star': Star,
  'database': Database,
  'desktop': Monitor,
  'activity': Activity,
  'heartbeat': Activity,
  'wifi-high': Wifi,
  'bug': Bug,
  'list-bullets': List,
  'list': List,
  'chart-line': LineChart,
  'squares-four': LayoutGrid,
  'question': HelpCircle,
  'check': Check,
  'pencil': Pencil,
  'pencil-simple': Pencil,
  'plug': Plug,
  'plus': Plus,
  'plus-circle': PlusCircle,
  'spinner': Loader2,
  'spinner-gap': Loader2,
  'circle-notch': Loader2,
  'check-circle': CheckCircle,
  'clock': Clock,
  'warning': AlertTriangle,
  'warning-circle': AlertTriangle,
  'x': X,
  'x-circle': XCircle,
  'github-logo': Github,
  'copy': Copy,
  'files': Files,
  'file': File,
  'git-branch': GitBranch,
  'caret-down': ChevronDown,
  'caret-up': ChevronUp,
  'caret-left': ChevronLeft,
  'caret-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'eye': Eye,
  'eye-slash': EyeOff,
  'trash': Trash2,
  'download': Download,
  'upload': Upload,
  'magnifying-glass': Search,
  'search': Search,
  'folder': Folder,
  'folder-open': FolderOpen,
  'code': Code,
  'terminal': Terminal,
  'play': Play,
  'pause': Pause,
  'stop': Square,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'dots-three': MoreHorizontal,
  'dots-three-vertical': MoreVertical,
  'info': Info,
  'lock': Lock,
  'lock-simple': Lock,
  'lock-open': Unlock,
  'lock-key-open': LockKeyholeOpen,
  'link': Link,
  'link-break': Link2Off,
  'cloud': Cloud,
  'sun': Sun,
  'moon': Moon,
  'palette': Palette,
  'sliders': Sliders,
  'faders': Sliders,
  'funnel': Filter,
  'funnel-simple': Filter,
  'sort-ascending': ArrowUpAZ,
  'sort-descending': ArrowDownZA,
  'text-aa': Type,
  'text-align-left': AlignLeft,
  'text-align-center': AlignCenter,
  'text-align-right': AlignRight,
  'image': Image,
  'note': StickyNote,
  'notebook': Book,
  'book': Book,
  'bookmark': Bookmark,
  'bookmark-simple': Bookmark,
  'calendar': Calendar,
  'clock-clockwise': RotateCw,
  'share': Share,
  'export': Share,
  'sign-out': LogOut,
  'sign-in': LogIn,
  'microphone': Mic,
  'microphone-slash': MicOff,
  'speaker-high': Volume2,
  'speaker-slash': VolumeX,
  'cpu': Cpu,
  'hard-drive': HardDrive,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'package': Package,
  'archive': Archive,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'shield-warning': ShieldAlert,
  'airplane': Plane,
  'anchor': Anchor,
  'at': AtSign,
  'battery-charging': BatteryCharging,
  'battery-full': BatteryFull,
  'chat': MessageSquare,
  'chat-circle': MessageSquare,
  'chat-text': MessageSquare,
  'message': MessageSquare,
  'file-plus': FilePlus,
  'folder-plus': FolderPlus,
  'circle-fill': Circle,
  'save': Save,
  'floppy-disk': Save,
  'history': History,
  'clock-counter-clockwise': History,
  'panel-left': PanelLeft,
  'sidebar-simple': PanelLeft,
  'cloud-arrow-down': CloudDownload,
  'device-mobile': Smartphone,
  'device-tablet': Tablet,
  'laptop': Laptop,
  'monitor': Monitor,
  'cursor-click': MousePointerClick,
  'selection': MousePointerClick,
  'qr-code': QrCode,
  'device-rotate': RefreshCw,
  'device-mobile-slash': Smartphone,
  'arrows-out': Maximize,
  'arrows-in': Minimize,
  'corners-out': Maximize,
  'corners-in': Minimize,
  'arrow-square-out': ExternalLink,
  'arrow-clockwise': RefreshCw,
  'arrow-counter-clockwise': RotateCcw,
  'edit': Pencil,
};

export interface IconProps {
  name: string;
  className?: string;
  size?: number | string;
  title?: string;
  style?: React.CSSProperties;
}

export const Icon: React.FC<IconProps> = ({ name, className = '', size = 16, title, style }) => {
  const IconComponent = iconMap[name] || iconMap[name.toLowerCase()] || HelpCircle;

  return <IconComponent className={className} size={size} title={title} style={style} />;
};
